"""add supplements and logs

Revision ID: 3641fb5e7e2e
Revises: 8f4b5e414c6d
Create Date: 2026-07-16 20:47:23.093402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3641fb5e7e2e'
down_revision: Union[str, Sequence[str], None] = '8f4b5e414c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('schedule_time', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplement_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplement_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('taken', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplement_logs')
    op.drop_table('supplements')
    # ### end Alembic commands ###
