"""add blood reports table

Revision ID: 8598518915be
Revises: 5b26e83d1ad5
Create Date: 2026-07-11 07:09:00.872946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8598518915be'
down_revision: Union[str, Sequence[str], None] = '5b26e83d1ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('vitamin_d', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('vitamin_b12', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('cholesterol_ldl', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('cholesterol_hdl', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('thyroid_tsh', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood_reports')
    # ### end Alembic commands ###
