"""add points and streak to user profiles

Revision ID: eb23792bb3ca
Revises: 3641fb5e7e2e
Create Date: 2026-07-16 20:49:02.410161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb23792bb3ca'
down_revision: Union[str, Sequence[str], None] = '3641fb5e7e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('points', sa.Integer(), nullable=False))
    op.add_column('user_profiles', sa.Column('streak_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'streak_days')
    op.drop_column('user_profiles', 'points')
    # ### end Alembic commands ###
